/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c WeatherIfAdaptor -a weatherifadaptor.h:weatherifadaptor.cpp foo.bar.weather.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef WEATHERIFADAPTOR_H_1403968478
#define WEATHERIFADAPTOR_H_1403968478

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface foo.bar.weather
 */
class WeatherIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "foo.bar.weather")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"foo.bar.weather\">\n"
"    <method name=\"currentTemp\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"cityId\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"currentPressure\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"cityId\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"result\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    WeatherIfAdaptor(QObject *parent);
    virtual ~WeatherIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    double currentTemp(int cityId);
    double currentPressure(int cityId);
    QString currentCondition(int cityId);
    QList<QString> searchCity(QString name);
    QList<QString> searchCity(double lon, double lat);
    QList<double> forecastTemp(int cityId);
    QList<double> forecastPressure(int cityId);
    QList<QString> forecastCondition(int cityId);

Q_SIGNALS: // SIGNALS
};

#endif
